# Generated by Django 6.0 on 2025-12-16 00:00

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                # User name fields
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                # Email as primary login field
                ('email', models.EmailField(error_messages={'unique': 'This email address is already registered. Please use a different email address.'}, max_length=254, unique=True)),
                # Username is optional and nullable
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                # Contact information
                ('country', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                # Personal information
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer-not-to-say', 'Prefer not to say')], max_length=20)),
                # Theme Settings
                ('theme_mode', models.CharField(choices=[('system', 'System'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=10)),
                ('accent_color', models.CharField(choices=[('blue', 'Blue'), ('emerald', 'Emerald'), ('amber', 'Amber'), ('indigo', 'Indigo')], default='blue', max_length=20)),
                ('font_family', models.CharField(choices=[('inter', 'Inter'), ('manrope', 'Manrope'), ('roboto', 'Roboto'), ('workSans', 'Work Sans')], default='inter', max_length=20)),
                ('font_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10)),
                ('compact_mode', models.BooleanField(default=False)),
                ('show_tooltips', models.BooleanField(default=True)),
                ('animations', models.BooleanField(default=True)),
                # Notification Settings
                ('email_alerts', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('sms_alerts', models.BooleanField(default=False)),
                ('digest_frequency', models.CharField(choices=[('instant', 'Instant'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20)),
                ('security_alerts', models.BooleanField(default=True)),
                ('mentions', models.BooleanField(default=True)),
                ('weekly_summary', models.BooleanField(default=True)),
                ('product_updates', models.BooleanField(default=False)),
                ('dnd_enabled', models.BooleanField(default=False)),
                ('dnd_start_time', models.CharField(default='21:00', max_length=5)),
                ('dnd_end_time', models.CharField(default='07:00', max_length=5)),
                # Privacy Settings
                ('profile_searchable', models.BooleanField(default=False)),
                ('messages_from_anyone', models.BooleanField(default=False)),
                ('show_online_status', models.BooleanField(default=True)),
                ('two_factor_enabled', models.BooleanField(default=True)),
                ('login_alerts', models.BooleanField(default=True)),
                ('analytics_enabled', models.BooleanField(default=True)),
                ('personalized_ads', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
