# Generated by Django 6.0 on 2025-12-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accent_color',
            field=models.CharField(choices=[('blue', 'Blue'), ('emerald', 'Emerald'), ('amber', 'Amber'), ('indigo', 'Indigo')], default='blue', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='analytics_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='digest_frequency',
            field=models.CharField(choices=[('instant', 'Instant'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='dnd_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='dnd_end_time',
            field=models.CharField(default='07:00', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='dnd_start_time',
            field=models.CharField(default='21:00', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='email_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mentions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='messages_from_anyone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='personalized_ads',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='product_updates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_searchable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='push_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='security_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='show_online_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_alerts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_mode',
            field=models.CharField(choices=[('system', 'System'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weekly_summary',
            field=models.BooleanField(default=True),
        ),
    ]
