# Generated by Django 6.0 on 2025-12-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_accent_color_user_analytics_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='animations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='compact_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='font_family',
            field=models.CharField(choices=[('inter', 'Inter'), ('manrope', 'Manrope'), ('roboto', 'Roboto'), ('workSans', 'Work Sans')], default='inter', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='show_tooltips',
            field=models.BooleanField(default=True),
        ),
    ]
